server:
  port: 8090

spring:
  main:
    allow-bean-definition-overriding: true
  profiles:
    active: db
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  servlet:
    multipart:
      enabled: true
      max-file-size: 3072MB
      max-request-size: 3072MB

logging:
  config: classpath:logback.xml

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.hx.collector
  map-underscore-to-camel-case: true